<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class LokasiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Truncate (kosongkan) tabel sebelum seeding agar data tidak duplikat
        DB::table('lokasis')->truncate();
        
        DB::table('lokasis')->insert(array (
  0 => 
  array (
    'nama_lokasi' => 'Candi Cangkuang',
    'kategori' => 'Budaya',
    'deskripsi' => 'Candi Hindu yang terletak di Kampung Pulo, Kecamatan Leles, Garut. Merupakan satu-satunya candi Hindu yang ditemukan di tatar Sunda.',
    'alamat' => 'Kampung Pulo, Cangkuang, Leles, Garut',
    'latitude' => '-7.1023129',
    'longitude' => '107.9200045',
    'foto' => 'lokasi/C56LOtfFe5jtTgMpgiWetEV2DGUWRIylKmHvqmgI.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-08-28T12:02:37.000000Z',
    'updated_at' => '2025-09-03T14:57:38.000000Z',
  ),
  1 => 
  array (
    'nama_lokasi' => 'Pantai Santolo',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Salah satu pantai paling populer di Garut dengan pasir putih dan pemandangan laut yang indah.',
    'alamat' => 'Kecamatan Cikelet, Garut Selatan',
    'latitude' => '-7.6599380',
    'longitude' => '107.6919130',
    'foto' => 'lokasi/WEuHYd7iytr2X6XCbfzhhtNDOoCHZoIAqJJ2DNvu.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-08-28T12:02:37.000000Z',
    'updated_at' => '2025-09-03T14:43:30.000000Z',
  ),
  2 => 
  array (
    'nama_lokasi' => 'Kawah Talaga Bodas',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Kawah vulkanik dengan danau berwarna putih kehijauan yang menawan, dikelilingi oleh perbukitan hijau.',
    'alamat' => 'Kecamatan Wanaraja, Garut',
    'latitude' => '-7.2120000',
    'longitude' => '108.0672000',
    'foto' => 'talaga_bodas.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-08-28T12:02:37.000000Z',
    'updated_at' => '2025-08-28T12:02:37.000000Z',
  ),
  3 => 
  array (
    'nama_lokasi' => 'De Wisdom Garut',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'De Wisdom Garut adalah sebuah villa dengan arsitektur modern yang terletak di atas bukit, menawarkan pemandangan lanskap alam Garut yang memesona, termasuk perbukitan hijau dan kebun teh yang membentang luas. Tempat ini sangat cocok untuk menikmati matahari terbit dan terbenam yang indah dalam suasana yang tenang dan sejuk.',
    'alamat' => 'Kp. Cimuncang, RT.03/RW.07, Rancabango, Kec. Tarogong Kaler, Kabupaten Garut, Jawa Barat 44151',
    'latitude' => '-7.1872323',
    'longitude' => '107.8596653',
    'foto' => 'lokasi-foto/MEEiqJmtoC3LzqU3cLU9B2LWta6zZtVGEEqE7ODB.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T09:24:32.000000Z',
    'updated_at' => '2025-09-02T09:24:32.000000Z',
  ),
  4 => 
  array (
    'nama_lokasi' => 'Wisata Garut Dinoland',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Berlokasi di kaki Gunung Guntur yang sejuk, Garut Dinoland adalah destinasi wisata edukatif bertema zaman purbakala pertama di Garut. Tempat ini mengajak Anda dan keluarga berpetualang di "dunia dinosaurus" dengan berbagai replika yang bisa bergerak dan mengeluarkan suara, sehingga terasa sangat nyata.',
    'alamat' => 'Kp. Cibolerang, RT.001/RW.010, Mekarjaya, Kec. Tarogong Kaler, Kabupaten Garut, Jawa Barat 44151',
    'latitude' => '-7.1931649',
    'longitude' => '107.8510480',
    'foto' => 'lokasi-foto/g4zLHrTfyCiq8F4qlr6vhaBiBgszxWSxQpwMQkAa.jpg',
    'ticket_url' => 'https://garutdinoland.com/tiket',
    'created_at' => '2025-09-02T09:27:44.000000Z',
    'updated_at' => '2025-09-03T04:58:06.000000Z',
  ),
  5 => 
  array (
    'nama_lokasi' => 'Wisata Alam Batu Lempar',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Wisata Alam Batu Lempar adalah destinasi wisata alam tersembunyi yang terletak di Garut, menawarkan keindahan sungai, bebatuan unik, serta air terjun yang masih sangat alami. Tempat ini cocok bagi Anda yang mencari suasana tenang, sejuk, dan petualangan di tengah alam.',
    'alamat' => 'Jl. Godog, Godog, Kec. Karangpawitan, Kabupaten Garut, Jawa Barat 44182',
    'latitude' => '-7.2553914',
    'longitude' => '107.9588483',
    'foto' => 'lokasi-foto/WoEVHShzQruCTm7X5DaA9jqIjJuGykD1DckaG7MZ.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T09:30:09.000000Z',
    'updated_at' => '2025-09-02T09:30:09.000000Z',
  ),
  6 => 
  array (
    'nama_lokasi' => 'Wisata Alam Darajat Garut',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Wisata Alam Darajat Garut adalah salah satu destinasi wisata paling populer di Garut, yang menawarkan perpaduan unik antara keindahan alam pegunungan yang sejuk dan wahana rekreasi modern. Terletak di dataran tinggi, tempat ini sangat terkenal dengan pemandian air panas alami yang bersumber langsung dari panas bumi.',
    'alamat' => 'Jl. Raya Darajat No.Km. 13, Karyamekar, Kec. Pasirwangi, Kabupaten Garut, Jawa Barat 44161',
    'latitude' => '-7.2175247',
    'longitude' => '107.7466984',
    'foto' => 'lokasi-foto/JJHgTTTkUCITQ0TxXOmERzAnhzh0dJhz5ukRs5Ck.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T09:33:07.000000Z',
    'updated_at' => '2025-09-02T09:33:07.000000Z',
  ),
  7 => 
  array (
    'nama_lokasi' => 'Alun-alun Garut',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Alun-alun Garut adalah jantung kota dan ruang terbuka publik yang ikonik, terletak di pusat Garut, Jawa Barat. Sebagai pusat kegiatan sosial dan budaya, alun-alun ini menjadi tempat berkumpul favorit bagi warga setempat maupun wisatawan, terutama saat sore hari dan akhir pekan.',
    'alamat' => 'Jl. Ahmad Yani No.22, Paminggir, Kec. Garut Kota, Kabupaten Garut, Jawa Barat 44118',
    'latitude' => '-7.2162221',
    'longitude' => '107.9014391',
    'foto' => 'lokasi-foto/cre7mUyi8yexMoDS99ZXmHPH7kxmQ4ghOp0AuK3Y.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T09:34:44.000000Z',
    'updated_at' => '2025-09-02T09:34:44.000000Z',
  ),
  8 => 
  array (
    'nama_lokasi' => 'Situ Bagendit',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Situ Bagendit adalah sebuah danau alami yang menawan, berlokasi di Garut, Jawa Barat. Nama "Bagendit" diambil dari legenda lokal yang menceritakan tentang seorang janda kaya yang serakah. Danau ini menawarkan perpaduan antara keindahan alam, legenda yang kental, dan berbagai wahana rekreasi yang cocok untuk liburan keluarga.',
    'alamat' => 'Sukamukti, Kec. Banyuresmi, Kabupaten Garut, Jawa Barat 44191',
    'latitude' => '-7.1608225',
    'longitude' => '107.9365842',
    'foto' => 'lokasi-foto/82TP4mPmp2Ttx3tj4Vfp4BP1cV3DNQOk2WviiQKH.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T09:37:05.000000Z',
    'updated_at' => '2025-09-02T09:37:05.000000Z',
  ),
  9 => 
  array (
    'nama_lokasi' => 'D Leuwi Garut',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'D\' Leuwi Garut adalah sebuah destinasi wisata modern yang mengusung konsep taman rekreasi air dan spot foto Instagramable. Terletak di daerah yang sejuk dan dikelilingi oleh perbukitan, tempat ini menawarkan pengalaman liburan yang menyegarkan dan penuh keseruan, sangat cocok untuk keluarga dan generasi muda.',
    'alamat' => 'Kp Panauwan RT 3/11, Jl. Pembangunan, Tarogong, Kabupaten Garut, Jawa Barat',
    'latitude' => '-7.2218659',
    'longitude' => '107.8843787',
    'foto' => 'lokasi-foto/CqNiN10kILF3uAxhIZF6uKSpIM0RKPzk0UekBD5O.png',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T09:40:14.000000Z',
    'updated_at' => '2025-09-02T09:40:14.000000Z',
  ),
  10 => 
  array (
    'nama_lokasi' => 'Awit Sinar Alam Darajat Garut',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Awit Sinar Alam Darajat adalah salah satu resor dan tempat wisata unggulan yang terletak di kawasan Dataran Tinggi Darajat, Garut. Destinasi ini menawarkan pengalaman liburan lengkap dengan perpaduan antara kolam air panas alami, wahana permainan air, dan pemandangan pegunungan yang menakjubkan.',
    'alamat' => 'Jl. Darajat Km No 24, Padaawas, Kec. Pasirwangi, Kabupaten Garut, Jawa Barat 44162',
    'latitude' => '-7.2185471',
    'longitude' => '107.7413314',
    'foto' => 'lokasi-foto/B0YO7cPylAs4EDLchQMwtbBUKh5SZCNRtMJdu8sw.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T09:43:07.000000Z',
    'updated_at' => '2025-09-02T09:43:07.000000Z',
  ),
  11 => 
  array (
    'nama_lokasi' => 'Karacak Valley',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Karacak Valley adalah sebuah destinasi wisata alam terpadu yang terletak di Garut, menawarkan perpaduan antara keindahan alam hutan pinus, perkebunan kopi, serta spot-spot rekreasi yang menarik. Berada di kaki Gunung Karacak, tempat ini menyuguhkan udara yang sejuk dan suasana yang tenang, cocok untuk melepas penat dari hiruk pikuk perkotaan.',
    'alamat' => 'Jalan Karacak Valley Margawati, Sukanegla, Kec. Garut Kota, Kabupaten Garut, Jawa Barat 44113',
    'latitude' => '-7.2693332',
    'longitude' => '107.9508654',
    'foto' => 'lokasi-foto/1XXQ6kXjnrrO0C9ICv72VMx5Nzg34vVoDmbSMVZu.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T09:44:47.000000Z',
    'updated_at' => '2025-09-02T09:44:47.000000Z',
  ),
  12 => 
  array (
    'nama_lokasi' => 'Edu Wisata Perlebahan Gunung Guntur',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Edu Wisata Perlebahan Gunung Guntur adalah destinasi wisata edukasi yang unik di Garut, menawarkan pengalaman belajar tentang dunia lebah dan madu secara langsung. Terletak di kaki Gunung Guntur yang sejuk, tempat ini menggabungkan edukasi, alam, dan rekreasi, sehingga cocok untuk dikunjungi oleh keluarga, pelajar, maupun para pecinta alam.',
    'alamat' => 'Aji, Jl. Letjen Ibrahim Adjie, Pasawahan, Kec. Tarogong Kaler, Kabupaten Garut, Jawa Barat 44151',
    'latitude' => '-7.1645352',
    'longitude' => '107.8796741',
    'foto' => 'lokasi-foto/nT9eEBc9b52e1Wm8MK6bxYtTXPRe3fywWwzUDjhF.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T09:46:49.000000Z',
    'updated_at' => '2025-09-02T09:46:49.000000Z',
  ),
  13 => 
  array (
    'nama_lokasi' => 'Darajat Pass',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Darajat Pass adalah salah satu destinasi wisata populer di kawasan Darajat, Garut, yang menawarkan perpaduan sempurna antara pemandian air panas, wahana rekreasi, dan panorama alam pegunungan yang menakjubkan. Tempat ini dikenal sebagai salah satu yang pertama kali mengembangkan konsep resort dan wisata air panas di dataran tinggi Darajat.',
    'alamat' => 'Jl. Puncak Darajat No.Km. 14, Karyamekar, Kec. Pasirwangi, Kabupaten Garut, Jawa Barat 44161',
    'latitude' => '-7.2174767',
    'longitude' => '107.7452618',
    'foto' => 'lokasi-foto/EO1UP4kUYOVVCg71j8z36X08vqstE5JOeKOw452f.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T09:49:01.000000Z',
    'updated_at' => '2025-09-02T09:49:01.000000Z',
  ),
  14 => 
  array (
    'nama_lokasi' => 'Wisata Sungai Ciharus',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Wisata Sungai Ciharus adalah destinasi alam tersembunyi yang menawarkan pengalaman petualangan di tengah keindahan alam Garut yang masih sangat asri. Terletak di kaki gunung dengan aliran sungai yang jernih, tempat ini sangat cocok bagi Anda yang menyukai aktivitas di luar ruangan dan mencari ketenangan jauh dari keramaian.',
    'alamat' => 'Kp.Cogreg, Dano, Kec. Leles, Kabupaten Garut, Jawa Barat 44152',
    'latitude' => '-7.1086469',
    'longitude' => '107.8615560',
    'foto' => 'lokasi-foto/9Py17lz4NQ8SzF27xL2HryT5sZUOzzPW0MRyXhX5.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T09:51:09.000000Z',
    'updated_at' => '2025-09-02T09:51:09.000000Z',
  ),
  15 => 
  array (
    'nama_lokasi' => 'Puncak Parabon Kamojang',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Puncak Parabon Kamojang adalah sebuah destinasi wisata alam di Garut yang menawarkan pemandangan sunrise yang spektakuler dan panorama danau vulkanik yang menawan. Berlokasi di kawasan Kamojang yang sejuk, tempat ini menjadi incaran para pencinta alam dan fotografer yang ingin menikmati keindahan alam dari ketinggian.',
    'alamat' => 'Jl. Raya Kamojang, Sukalaksana, Kec. Samarang, Kabupaten Garut, Jawa Barat 44161',
    'latitude' => '-7.1727023',
    'longitude' => '107.8007824',
    'foto' => 'lokasi-foto/nUD4iWvLcabgHr2YqKV6LcnkhxrcdLqF6uzANgKb.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T09:53:57.000000Z',
    'updated_at' => '2025-09-02T09:53:57.000000Z',
  ),
  16 => 
  array (
    'nama_lokasi' => 'Talangseng (tubing)',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Talangseng adalah destinasi wisata alam yang menawarkan pengalaman river tubing atau meluncur di atas ban dalam menyusuri aliran sungai yang jernih. Terletak di Garut, tempat ini memberikan sensasi petualangan yang seru dan menyegarkan, sangat cocok bagi para pencari adrenalin dan pencinta alam.',
    'alamat' => 'Margawati, Kec. Garut Kota, Kabupaten Garut, Jawa Barat 44181',
    'latitude' => '-7.2417909',
    'longitude' => '107.9109225',
    'foto' => 'lokasi-foto/SAQDIudCAzEjHBxGBVVeG9HBIvoLuQeqNfnMvPvF.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T09:55:56.000000Z',
    'updated_at' => '2025-09-02T09:55:56.000000Z',
  ),
  17 => 
  array (
    'nama_lokasi' => 'Desa Wisata Saung Ciburial',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Desa Wisata Saung Ciburial adalah destinasi liburan yang menawarkan pengalaman unik untuk kembali ke alam dan menikmati kehidupan pedesaan yang damai. Terletak di Garut, tempat ini mengusung konsep wisata edukasi yang berfokus pada kebudayaan Sunda, pertanian, dan peternakan.',
    'alamat' => 'Sukalaksana, Kec. Samarang, Kabupaten Garut, Jawa Barat 44161',
    'latitude' => '-7.2047648',
    'longitude' => '107.8122865',
    'foto' => 'lokasi-foto/2u5UNkApmpr9bwPc4cJl7Y8WLY6Ctl6P8ShYUkkE.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T09:57:43.000000Z',
    'updated_at' => '2025-09-02T09:57:43.000000Z',
  ),
  18 => 
  array (
    'nama_lokasi' => 'Gunung Putri Intan Dewata',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Gunung Putri Intan Dewata adalah destinasi wisata spiritual dan alam yang unik di Garut. Tempat ini dikenal sebagai lokasi petilasan atau tempat bersejarah yang disakralkan, yang sering dikunjungi oleh para peziarah. Selain itu, keindahan alamnya yang berada di ketinggian juga menjadikannya tempat favorit bagi mereka yang ingin menikmati pemandangan kota dari atas.',
    'alamat' => 'Mekarjaya, Kec. Tarogong Kaler, Kabupaten Garut, Jawa Barat 44151',
    'latitude' => '-7.1799245',
    'longitude' => '107.8491388',
    'foto' => 'lokasi-foto/aITiOp7TcMnkRqdAYVrjl4p94BfTAZ8PK8AtrN2x.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T10:00:11.000000Z',
    'updated_at' => '2025-09-02T10:00:11.000000Z',
  ),
  19 => 
  array (
    'nama_lokasi' => 'Desa Wisata Situ Cangkuang',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Desa Wisata Situ Cangkuang adalah destinasi sejarah dan budaya yang berpadu dengan keindahan alam. Terletak di Leles, Garut, tempat ini terkenal dengan Candi Cangkuang, satu-satunya candi Hindu di Jawa Barat, yang berada di tengah sebuah danau bernama Situ Cangkuang.',
    'alamat' => 'Kp. Lolohan, RT.002/RW.013, Cangkuang, Leles, Garut Regency, West Java 44152',
    'latitude' => '-7.1040683',
    'longitude' => '107.9206983',
    'foto' => 'lokasi-foto/TagcrXZldmh9OSVE5MDF7DCXS4SkBN2xSKzK7XC8.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T10:04:08.000000Z',
    'updated_at' => '2025-09-02T10:04:08.000000Z',
  ),
  20 => 
  array (
    'nama_lokasi' => 'Curug Citiis',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Curug Citiis adalah air terjun alami yang terletak di kaki Gunung Guntur, Garut. Nama "Citiis" berasal dari bahasa Sunda yang berarti air dingin, sesuai dengan karakteristik airnya yang sangat sejuk dan menyegarkan. Tempat ini menawarkan perpaduan antara keindahan alam, suasana yang tenang, dan pengalaman mendaki yang menantang.',
    'alamat' => 'Pasawahan, Kec. Tarogong Kaler, Kabupaten Garut, Jawa Barat 44151',
    'latitude' => '-7.1567848',
    'longitude' => '107.8657671',
    'foto' => 'lokasi-foto/Vdlozd9SYeoIPOgULYBcolBmUenvFiIov2nJjYPG.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T10:06:08.000000Z',
    'updated_at' => '2025-09-02T10:06:08.000000Z',
  ),
  21 => 
  array (
    'nama_lokasi' => 'Desa Wisata Mulakeudeu',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Desa Wisata Mulakeudeu adalah destinasi wisata berbasis alam dan budaya yang menawarkan pengalaman unik untuk merasakan kehidupan pedesaan yang damai dan menikmati keindahan alam pegunungan di Garut. Berlokasi di lereng Gunung Guntur, desa ini terkenal dengan udara sejuk, panorama persawahan yang bertingkat, serta keramahan penduduknya.',
    'alamat' => 'Jl. Sucinaraja, Kp Mulakeudeu, Sukalaksana, Kec. Sucinaraja, Kabupaten Garut, Jawa Barat 44151',
    'latitude' => '-7.2073255',
    'longitude' => '107.9930986',
    'foto' => 'lokasi-foto/KVlr8VuXfJMJDEspfPYTY0BgjQDDn7vdveUHs9Hg.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T10:08:11.000000Z',
    'updated_at' => '2025-09-02T10:08:11.000000Z',
  ),
  22 => 
  array (
    'nama_lokasi' => 'Taman Air Sabda Alam',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Taman Air Sabda Alam adalah destinasi wisata air terbesar dan salah satu yang paling populer di Kabupaten Garut. Terletak di kawasan Cipanas yang sejuk, tempat ini menawarkan perpaduan sempurna antara rekreasi air modern dengan pemandangan alam perbukitan yang asri, menjadikannya pilihan ideal untuk liburan keluarga.',
    'alamat' => 'Jl. Raya Cipanas, Cimanganten, Kec. Tarogong Kaler, Kabupaten Garut, Jawa Barat 44151',
    'latitude' => '-7.1811019',
    'longitude' => '107.8750500',
    'foto' => 'lokasi-foto/elCV3mOjqw6r06tYQOIjBY68OcHhago1p9MiYmMv.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T10:09:58.000000Z',
    'updated_at' => '2025-09-02T10:09:58.000000Z',
  ),
  23 => 
  array (
    'nama_lokasi' => 'Antapura De Djati',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Antapura De Djati adalah destinasi wisata yang menawarkan perpaduan antara keindahan alam dan konsep modern yang unik. Berlokasi di pinggir Danau Cileunca, tempat ini dikenal dengan pemandangan danau dan perbukitan yang menawan, serta beragam spot foto yang dirancang secara artistik.',
    'alamat' => 'Cibiuk Kaler, Kec. Cibiuk, Kabupaten Garut, Jawa Barat',
    'latitude' => '-7.0609630',
    'longitude' => '107.9652219',
    'foto' => 'lokasi-foto/PxJvKHRgJo1lNUYUNpV5N5ABSne0Ld19jFrzOIGf.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T11:39:49.000000Z',
    'updated_at' => '2025-09-02T11:39:49.000000Z',
  ),
  24 => 
  array (
    'nama_lokasi' => 'Desa Wisata Sindangkasih',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Desa Wisata Sindangkasih adalah destinasi yang menawarkan pengalaman liburan yang berfokus pada kebudayaan, alam, dan keramahan masyarakatnya. Terletak di Garut, desa ini dikenal dengan keindahan alam persawahan, keunikan arsitektur rumah tradisional, serta seni dan budaya yang masih terjaga.',
    'alamat' => 'Jl. Garut - Tasikmalaya No.Km 16, Sukamaju, Kec. Cilawu, Kabupaten Garut, Jawa Barat 44181',
    'latitude' => '-7.3257721',
    'longitude' => '107.9419343',
    'foto' => 'lokasi-foto/wyfD5PUIyeq3ysNHi4607KMNALT4LsbHcmS8yYjf.jpg',
    'ticket_url' => 'https://www.instagram.com/desawisatasindangkasih/',
    'created_at' => '2025-09-02T11:41:20.000000Z',
    'updated_at' => '2025-09-03T05:39:41.000000Z',
  ),
  25 => 
  array (
    'nama_lokasi' => 'Kolong Langit Coffee Camp',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Kolong Langit Coffee Camp adalah sebuah destinasi wisata unik di Garut yang menggabungkan konsep kafe, tempat berkemah (camping), dan penginapan, semuanya berada di tengah keindahan alam pegunungan. Terletak di lereng Pegunungan Karacak, tempat ini menawarkan udara sejuk dan pemandangan hutan pinus yang menenangkan, sangat cocok untuk bersantai dan "menghilangkan penat" (healing).',
    'alamat' => 'Cilawu, Kec. Cilawu, Kabupaten Garut, Jawa Barat 44181',
    'latitude' => '-7.2816516',
    'longitude' => '107.9350862',
    'foto' => 'lokasi-foto/Nt5gSDQu0ZbqwnKVqm6GdzuQ9ZSQnFbQrJNxX9hm.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T11:42:47.000000Z',
    'updated_at' => '2025-09-02T11:42:47.000000Z',
  ),
  26 => 
  array (
    'nama_lokasi' => 'Cilopang adventure camp',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Cilopang Adventure Camp adalah destinasi wisata alam terpadu yang menawarkan pengalaman berkemah, rekreasi air, dan berbagai wahana petualangan seru. Terletak di Garut, tempat ini dikenal dengan suasana pegunungan yang sejuk dan pemandangan hutan pinus yang menawan, menjadikannya pilihan ideal untuk liburan keluarga atau kegiatan luar ruangan bersama teman.',
    'alamat' => 'Rancabango, Kec. Tarogong Kaler, Kabupaten Garut, Jawa Barat 44151',
    'latitude' => '-7.1832485',
    'longitude' => '107.8700319',
    'foto' => 'lokasi-foto/oZZ9karE743SDCidP4ai1quND7V9tOl6V4Tv3qQn.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T11:44:34.000000Z',
    'updated_at' => '2025-09-02T11:44:34.000000Z',
  ),
  27 => 
  array (
    'nama_lokasi' => 'Curug Ciharus Dano Leles',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Curug Ciharus adalah destinasi air terjun alami yang berlokasi di kawasan Dano, Leles, Garut. Sesuai dengan namanya yang berasal dari bahasa Sunda yang berarti air dingin, air terjun ini menawarkan kesegaran dan keindahan alam yang masih sangat asri, jauh dari keramaian kota.',
    'alamat' => 'Dano, Kec. Leles, Kabupaten Garut, Jawa Barat 44152',
    'latitude' => '-7.1203943',
    'longitude' => '107.8488934',
    'foto' => 'lokasi-foto/Ce573Bcj54xJA1TeRrsmdURxT9V7OfgG3Y3SL2Aq.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T11:47:11.000000Z',
    'updated_at' => '2025-09-02T11:47:11.000000Z',
  ),
  28 => 
  array (
    'nama_lokasi' => 'Kawah Darajat',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Kawah Darajat adalah destinasi wisata alam yang menawarkan pemandangan unik dan edukatif, berbeda dari tempat wisata air panas di sekitarnya. Terletak di dataran tinggi Darajat, kawah ini merupakan pusat aktivitas geotermal yang menghasilkan uap panas bumi, menciptakan suasana yang misterius dan menakjubkan.',
    'alamat' => 'Padaawas, Pasirwangi, Sarimukti, Kec. Pasirwangi, Kabupaten Garut, Jawa Barat 44161',
    'latitude' => '-7.2285392',
    'longitude' => '107.7284786',
    'foto' => 'lokasi-foto/lGzepAmY1S68t5pUHlMJeIKagi9EP5iGj6U5sANP.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-02T11:50:28.000000Z',
    'updated_at' => '2025-09-02T11:50:28.000000Z',
  ),
  29 => 
  array (
    'nama_lokasi' => 'Curug Orok',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Curug Orok adalah salah satu air terjun paling terkenal dan mudah diakses di Garut, menawarkan keindahan alam yang memukau dan legenda lokal yang menyentuh hati. Terletak di daerah Cikajang, curug ini dikelilingi oleh perkebunan teh yang luas dan udara yang sangat sejuk.',
    'alamat' => 'Jl. Curug Orok, Cikandang, Kec. Cikajang, Kabupaten Garut, Jawa Barat 44171',
    'latitude' => '-7.3732387',
    'longitude' => '107.7409893',
    'foto' => 'lokasi/AoNM2ekgd2J64Xe2dNwmd4kgNRg0UmKQDSsmq5Ji.png',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T05:48:13.000000Z',
    'updated_at' => '2025-09-03T06:00:05.000000Z',
  ),
  30 => 
  array (
    'nama_lokasi' => 'Taman Wisata Alam Gunung Papandayan',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'TWA (Taman Wisata Alam) Gunung Papandayan adalah salah satu destinasi pendakian dan wisata alam paling populer di Garut. Gunung Papandayan dikenal dengan pemandangannya yang unik dan relatif mudah diakses, menjadikannya pilihan favorit bagi pendaki pemula maupun wisatawan yang ingin menikmati keindahan alam pegunungan.',
    'alamat' => 'Jl. Kawah Papandayan, Sirnajaya, Kec. Cisurupan, Kabupaten Garut, Jawa Barat 44163',
    'latitude' => '-7.3040299',
    'longitude' => '107.7422767',
    'foto' => 'lokasi/2eqO3cPf22I2zDzPy43R8DqPVlGtprAHxzwDh0sk.png',
    'ticket_url' => 'https://www.instagram.com/twa.gunungpapandayangarut/',
    'created_at' => '2025-09-03T05:51:07.000000Z',
    'updated_at' => '2025-09-03T05:59:52.000000Z',
  ),
  31 => 
  array (
    'nama_lokasi' => 'Gunung Cikuray',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Gunung Cikuray adalah gunung tertinggi keempat di Jawa Barat dan merupakan salah satu destinasi pendakian paling favorit di Garut. Gunung ini dikenal dengan karakternya yang menantang dan pemandangan puncaknya yang luar biasa, menjadikannya incaran bagi para pendaki, baik pemula maupun yang sudah berpengalaman.',
    'alamat' => 'Dangiang, Kec. Cilawu, Kabupaten Garut, Jawa Barat',
    'latitude' => '-7.3183286',
    'longitude' => '107.8601717',
    'foto' => 'lokasi/Sy27qYVncKq7vtGS9hhRn6RHkKjus0N29DlpGqx5.jpg',
    'ticket_url' => 'https://www.instagram.com/gunungcikuraygarut/',
    'created_at' => '2025-09-03T06:27:48.000000Z',
    'updated_at' => '2025-09-03T06:27:48.000000Z',
  ),
  32 => 
  array (
    'nama_lokasi' => 'Pos 1 Pendakian Gunung Cikuray via Kiara Janggot',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Gunung Cikuray adalah gunung tertinggi keempat di Jawa Barat dan merupakan salah satu destinasi pendakian paling favorit di Garut. Gunung ini dikenal dengan karakternya yang menantang dan pemandangan puncaknya yang luar biasa, menjadikannya incaran bagi para pendaki, baik pemula maupun yang sudah berpengalaman.',
    'alamat' => 'Dangiang, Kec. Cilawu, Kabupaten Garut, Jawa Barat 44181',
    'latitude' => '-7.2995141',
    'longitude' => '107.8782390',
    'foto' => 'lokasi/CwvLISPRdjuztXcyBCNvgACTQ8gD3DFi5FCw8t9z.jpg',
    'ticket_url' => 'https://www.instagram.com/gunungcikuraygarut/',
    'created_at' => '2025-09-03T06:28:45.000000Z',
    'updated_at' => '2025-09-03T06:28:45.000000Z',
  ),
  33 => 
  array (
    'nama_lokasi' => 'Gunung Guntur',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Gunung Guntur adalah gunung berapi aktif yang terletak di Garut, menawarkan pengalaman pendakian unik dengan karakter jalur yang kering dan terbuka. Dikenal dengan puncaknya yang tandus seperti padang savana, gunung ini menjadi salah satu tujuan favorit bagi para pendaki yang ingin menikmati pemandangan menawan dari ketinggian tanpa harus menempuh waktu lama.',
    'alamat' => 'Sukawangi, Kec. Tarogong Kaler, Kabupaten Garut, Jawa Barat',
    'latitude' => '-7.1497685',
    'longitude' => '107.8376287',
    'foto' => 'lokasi/SdB2jS0dJV4Z2RU5EyGPdMnleHrJwHOXmveZ3Wsg.jpg',
    'ticket_url' => 'https://www.instagram.com/gunung_guntur/',
    'created_at' => '2025-09-03T06:31:40.000000Z',
    'updated_at' => '2025-09-03T06:31:40.000000Z',
  ),
  34 => 
  array (
    'nama_lokasi' => 'Gunug Haruman',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Gunung Haruman adalah salah satu destinasi wisata alam dan spiritual di Garut yang menawarkan perpaduan antara keindahan alam, ketenangan, dan nilai historis. Terletak di wilayah Kadungora, gunung ini sering dikunjungi oleh peziarah maupun pencinta alam yang mencari suasana damai.',
    'alamat' => 'Karanganyar, Kec. Leuwigoong, Kabupaten Garut, Jawa Barat',
    'latitude' => '-7.0721414',
    'longitude' => '107.9438360',
    'foto' => 'lokasi/WFjjkvDci2MOohCs8n6CbmiD1TStOkJ5cTmezKCT.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T06:35:36.000000Z',
    'updated_at' => '2025-09-03T06:35:36.000000Z',
  ),
  35 => 
  array (
    'nama_lokasi' => 'Gunung Telaga Bodas',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Gunung Telaga Bodas adalah sebuah kawah vulkanik dengan danau berwarna putih kehijauan yang menawan, dikelilingi oleh perbukitan hijau. Destinasi ini menawarkan pemandangan alam yang unik, udara sejuk, dan suasana yang tenang, menjadikannya tempat ideal untuk relaksasi dan fotografi.',
    'alamat' => 'Sundakerta, Kec. Sukahening, Kabupaten Tasikmalaya, Jawa Barat',
    'latitude' => '-7.2067647',
    'longitude' => '108.0707722',
    'foto' => 'lokasi/0BGeGsOh5P8Qg5KPyTIIXm2eMMILRPIzW1rZf3u6.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T06:38:20.000000Z',
    'updated_at' => '2025-09-03T06:38:20.000000Z',
  ),
  36 => 
  array (
    'nama_lokasi' => 'Gunung Kamojang',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Berdasarkan informasi yang ada, Gunung Kamojang adalah sebuah gunung berapi aktif yang dikenal karena aktivitas geotermalnya. Kawasan ini lebih populer sebagai Kawah Kamojang karena fenomena alam yang paling menonjol adalah kawah-kawah yang mengeluarkan uap panas bumi. Gunung ini terletak di perbatasan antara Kabupaten Garut dan Kabupaten Bandung, Jawa Barat.',
    'alamat' => 'Loa, Kec. Paseh, Kabupaten Bandung, Jawa Barat',
    'latitude' => '-7.1229979',
    'longitude' => '107.7999997',
    'foto' => 'lokasi/vA9j1kfyyCYasmQsza2SgriREMYnVuuzubn0KbqO.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T06:40:14.000000Z',
    'updated_at' => '2025-09-03T06:40:14.000000Z',
  ),
  37 => 
  array (
    'nama_lokasi' => 'Kawah Papandayan',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Kawah Papandayan adalah salah satu destinasi utama di TWA Gunung Papandayan. Kawah ini merupakan bagian dari gunung berapi yang masih aktif, menyuguhkan pemandangan lanskap geotermal yang unik dan dramatis. Udara yang sejuk di kawasan Garut berpadu dengan uap panas dan aroma belerang yang keluar dari dalam bumi, menciptakan pengalaman yang tak terlupakan.',
    'alamat' => 'Sirnajaya, Kec. Cisurupan, Kabupaten Garut, Jawa Barat 44163',
    'latitude' => '-7.3143298',
    'longitude' => '107.7316426',
    'foto' => 'lokasi/IrgxMxmtam23XHhtzARMxoKDEsFI9i6stLnCbG9M.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T06:42:38.000000Z',
    'updated_at' => '2025-09-03T06:42:38.000000Z',
  ),
  38 => 
  array (
    'nama_lokasi' => 'Hutan Mati Gunung Papandayan',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Hutan Mati Papandayan adalah salah satu spot paling ikonik dan dramatis di kawasan Taman Wisata Alam Gunung Papandayan, Garut. Sesuai namanya, Hutan Mati adalah area hutan yang seluruh pohonnya hangus dan kering akibat erupsi Gunung Papandayan pada tahun 2002.',
    'alamat' => 'Karamat Wangi, Kec. Cisurupan, Kabupaten Garut, Jawa Barat 44163',
    'latitude' => '-7.3180352',
    'longitude' => '107.7266179',
    'foto' => 'lokasi/qsi72tKvei4AsHu1V2epR3Ce4DS63LaKxYv9praw.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T14:35:10.000000Z',
    'updated_at' => '2025-09-03T14:35:10.000000Z',
  ),
  39 => 
  array (
    'nama_lokasi' => 'Taman Teletubies Sayang Heulang',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Berdasarkan informasi yang ditemukan, yang dimaksud dengan "Taman Teletubies Sayang Heulang" adalah Bukit Teletubbies yang berlokasi di dekat Pantai Sayang Heulang, Garut Selatan. Bukit ini dinamakan demikian karena bentuknya yang bergelombang dan ditutupi padang rumput hijau, sangat mirip dengan lanskap di serial anak-anak populer, Teletubbies.',
    'alamat' => 'Mancagahar, Kec. Pameungpeuk, Kabupaten Garut, Jawa Barat 44175',
    'latitude' => '-7.6637278',
    'longitude' => '107.7045685',
    'foto' => 'lokasi/PKrUfF0L0TPQeOsQ9cKzEA5PZVyEV6zikjdHHnN0.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T14:38:21.000000Z',
    'updated_at' => '2025-09-03T14:38:21.000000Z',
  ),
  40 => 
  array (
    'nama_lokasi' => 'Puncak Guha',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Berdasarkan informasi yang ditemukan, Puncak Guha adalah sebuah destinasi wisata alam yang terletak di pesisir selatan Garut, tepatnya di Desa Sinarjaya, Kecamatan Bungbulang. Dinamakan "Guha" karena terdapat gua alami yang dihuni kelelawar di bawah tebingnya. Tempat ini menawarkan pemandangan tebing curam yang langsung menghadap Samudra Hindia, memberikan panorama laut lepas yang memukau.',
    'alamat' => 'Sinarjaya, Kec. Bungbulang, Kabupaten Garut, Jawa Barat 44165',
    'latitude' => '-7.5361351',
    'longitude' => '107.4971953',
    'foto' => 'lokasi/1sPySF5A0OndxilpuhCa1CLIv0A3OQDtKTKY2zBv.png',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T14:41:02.000000Z',
    'updated_at' => '2025-09-03T14:41:02.000000Z',
  ),
  41 => 
  array (
    'nama_lokasi' => 'Bukit Nangklak',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Bukit Nangklak adalah destinasi wisata alam yang menawarkan pemandangan menakjubkan dari ketinggian di Garut. Berlokasi di daerah yang sejuk dan asri, bukit ini sangat populer di kalangan pencinta alam dan fotografer, terutama karena pemandangan matahari terbit dan "samudra awan" yang begitu mempesona.',
    'alamat' => 'Sirnajaya, Kec. Cisurupan, Kabupaten Garut, Jawa Barat 44163',
    'latitude' => '-7.3009870',
    'longitude' => '107.7556857',
    'foto' => 'lokasi/vJtiQ8QwIFSG0FvRHtgUavP6QygPwTKvHvgOzl6t.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T14:43:13.000000Z',
    'updated_at' => '2025-09-03T14:43:13.000000Z',
  ),
  42 => 
  array (
    'nama_lokasi' => 'Pantai Sayang Heulang Garut',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Pantai Sayang Heulang adalah salah satu destinasi wisata populer di pesisir selatan Kabupaten Garut, Jawa Barat. Terletak di Desa Mancagahar, pantai ini dikenal karena keindahan alamnya yang masih alami, dengan hamparan pasir putih yang lembut dan air laut yang jernih. Salah satu ciri khasnya adalah adanya batu karang raksasa yang tersebar hingga ke tengah laut, yang saat air surut bisa dijelajahi. Nama "Sayang Heulang" sendiri berasal dari legenda setempat tentang seorang putri yang menyelamatkan anak elang.',
    'alamat' => 'Mancagahar, Kec. Pameungpeuk, Kabupaten Garut, Jawa Barat 44175',
    'latitude' => '-7.6667058',
    'longitude' => '107.6963395',
    'foto' => 'lokasi/zBsNpGAzjONLDQLIeiSc5Lducvrw8T4xQx2AbB6z.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T14:44:49.000000Z',
    'updated_at' => '2025-09-03T14:44:49.000000Z',
  ),
  43 => 
  array (
    'nama_lokasi' => 'Pantai Rancabuaya',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Pantai Rancabuaya merupakan salah satu destinasi wisata pantai yang terkenal di selatan Garut, Jawa Barat. Pantai ini terletak di Desa Purbayani, Kecamatan Caringin. Pantai ini memiliki karakteristik yang unik dengan hamparan pasir putih yang lembut dan ombak yang besar karena langsung menghadap Samudra Hindia. Keunikan lainnya adalah keberadaan batu karang raksasa yang tersebar di sepanjang pantai.',
    'alamat' => 'Desa Purbayani, Kecamatan Caringin, Kabupaten Garut, Jawa Barat 44175',
    'latitude' => '-7.5283108',
    'longitude' => '107.4803783',
    'foto' => 'lokasi/mT3oAbqMdco0NtJA4lyOVSvzxMe0JO9KJR7SCj5E.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T14:47:57.000000Z',
    'updated_at' => '2025-09-03T14:47:57.000000Z',
  ),
  44 => 
  array (
    'nama_lokasi' => 'Pantai Karang Paranje',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Pantai Karang Paranje adalah salah satu pantai tersembunyi yang menawarkan keindahan alami di pesisir selatan Garut, Jawa Barat. Terletak di Desa Karyasari, Kecamatan Cibalong, pantai ini dikenal dengan tebing-tebing karang yang menjulang tinggi, ombak Samudra Hindia yang besar, serta suasana yang masih sangat alami dan belum terlalu ramai.',
    'alamat' => 'Karyasari, Kec. Cibalong, Kabupaten Garut, Jawa Barat 44176',
    'latitude' => '-7.6838480',
    'longitude' => '107.7948036',
    'foto' => 'lokasi/WrRcTKh5aMHDiucd6vevlXx9UlFRNGthrVEvbhe3.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T14:49:00.000000Z',
    'updated_at' => '2025-09-03T14:49:00.000000Z',
  ),
  45 => 
  array (
    'nama_lokasi' => 'Pantai Cijeruk Indah',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Pantai Cijeruk Indah adalah "surga tersembunyi" di Kabupaten Garut, Jawa Barat, yang terletak di Desa Sancang, Kecamatan Cibalong. Pantai ini dikenal karena suasananya yang tenang dan alami, menjadikannya pilihan ideal bagi mereka yang ingin melarikan diri dari keramaian kota.',
    'alamat' => 'Sagara, Kec. Pameungpeuk, Kabupaten Garut, Jawa Barat 44176',
    'latitude' => '-7.7044368',
    'longitude' => '107.8360154',
    'foto' => 'lokasi/5nAsd8Wtqmp1yyOj94TW6OACSOx7YBgts01g34qr.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T14:50:30.000000Z',
    'updated_at' => '2025-09-03T14:50:30.000000Z',
  ),
  46 => 
  array (
    'nama_lokasi' => 'Pantai Taman Manalusu',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Pantai Taman Manalusu, atau yang juga dikenal sebagai Pantai Manalusu, adalah destinasi wisata yang terletak di Desa Cigadog, Kecamatan Cikelet, Kabupaten Garut, Jawa Barat. Pantai ini mendapatkan namanya dari seorang pegawai perkebunan bernama Karl Manalusu Tambunan yang konon pertama kali menemukan dan menata area ini. Nama "Taman" diberikan karena pantai ini memiliki panorama alam yang unik, yaitu gugusan karang dan rumput laut yang tumbuh subur di sepanjang pesisir.',
    'alamat' => 'Cigadog, Kec. Cikelet, Kabupaten Garut, Jawa Barat 44177',
    'latitude' => '-7.5899917',
    'longitude' => '107.6249030',
    'foto' => 'lokasi/szUuuNNQ2rZLT5hHbNbxYnEjPUOwqsFWSQDcHouU.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T14:52:15.000000Z',
    'updated_at' => '2025-09-03T14:52:15.000000Z',
  ),
  47 => 
  array (
    'nama_lokasi' => 'Pantai Cicalobak',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Pantai Cicalobak adalah salah satu surga tersembunyi di pesisir selatan Garut, tepatnya di Kecamatan Mekarmukti. Pantai ini terkenal karena keindahan tebing-tebing karangnya yang menjulang tinggi, pasir putih, dan ombak Samudra Hindia yang besar, menciptakan lanskap yang dramatis dan berbeda dari pantai lainnya.',
    'alamat' => 'Karangwangi, Kec. Depok, Jawa Barat 44165',
    'latitude' => '-7.5451034',
    'longitude' => '107.5292615',
    'foto' => 'lokasi/heGFQyyg5g8XMBldFQLSWv5wiguXtWp6MIJQzmtu.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T14:53:36.000000Z',
    'updated_at' => '2025-09-03T14:53:36.000000Z',
  ),
  48 => 
  array (
    'nama_lokasi' => 'Pantai Sodong Lalay',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Pantai Sodong Lalay adalah salah satu "harta karun" tersembunyi di Garut Selatan, yang terletak di Desa Karangwangi, Kecamatan Mekarmukti. Pantai ini menawarkan suasana yang tenang dan eksotis karena belum terlalu ramai dikunjungi.',
    'alamat' => 'Kp. Cigoa, Karangwangi, Mekarmukti, Karangwangi, Garut, Kabupaten Garut, Jawa Barat 44165',
    'latitude' => '-7.5525028',
    'longitude' => '107.5375885',
    'foto' => 'lokasi/WFbGFWL3pDrCGUmefs4RbL823y07KdVhZ3SGigMt.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T14:54:29.000000Z',
    'updated_at' => '2025-09-03T14:54:29.000000Z',
  ),
  49 => 
  array (
    'nama_lokasi' => 'Pantai Karang Tepas',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Pantai Karang Tepas adalah salah satu destinasi wisata pantai yang menawan di Garut Selatan, yang terletak di Desa Karangwangi, Kecamatan Mekarmukti. Pantai ini terkenal dengan keindahan tebing-tebing karang raksasa yang langsung berhadapan dengan Samudra Hindia, menciptakan pemandangan yang dramatis dan berbeda dari pantai berpasir pada umumnya.',
    'alamat' => 'Purbayani, Kec. Caringin, Kabupaten Garut, Jawa Barat 44166',
    'latitude' => '-7.5361425',
    'longitude' => '107.4822827',
    'foto' => 'lokasi/9z1wApYbRzQmXkDjEvsdZ0VTPCXwpmd0gcKELceZ.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T14:55:24.000000Z',
    'updated_at' => '2025-09-03T14:55:24.000000Z',
  ),
  50 => 
  array (
    'nama_lokasi' => 'Pantai Gunung Geder',
    'kategori' => 'Pariwisata',
    'deskripsi' => 'Pantai Gunung Geder adalah salah satu pantai yang masih tergolong alami dan tenang di pesisir selatan Garut, Jawa Barat. Terletak di Desa Sancang, Kecamatan Cibalong, pantai ini menawarkan perpaduan pemandangan laut yang eksotis dengan keberadaan sebuah bukit kecil yang menjulang, sesuai dengan namanya "Gunung Geder".',
    'alamat' => 'Cijambe, Kec. Cikelet, Kabupaten Garut, Jawa Barat 44177',
    'latitude' => '-7.6166393',
    'longitude' => '107.6634957',
    'foto' => 'lokasi/AZgpIa2sy7soT5ZgR0GeMHMUfi7rK0rbxWCzlVLn.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T14:56:26.000000Z',
    'updated_at' => '2025-09-03T14:56:26.000000Z',
  ),
  51 => 
  array (
    'nama_lokasi' => 'Kampung Adat Pulo',
    'kategori' => 'Budaya',
    'deskripsi' => 'Kampung Adat Pulo adalah sebuah desa adat yang unik dan bersejarah, terletak di sebuah pulau kecil di tengah Situ Cangkuang, Leles, Garut. Kampung ini dikenal karena keunikan tradisi dan aturan adatnya yang masih dipegang teguh oleh penduduknya hingga saat ini.',
    'alamat' => 'Jl. Darajat, Cangkuang, Kec. Leles, Kabupaten Garut, Jawa Barat 44119',
    'latitude' => '-7.1029907',
    'longitude' => '107.9180025',
    'foto' => 'lokasi/kTtFNf6RxV1zq0yb6Qp2dWpiEmQYAVJjwktBnTKd.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T14:58:45.000000Z',
    'updated_at' => '2025-09-03T14:58:45.000000Z',
  ),
  52 => 
  array (
    'nama_lokasi' => 'Kampung Dukuh',
    'kategori' => 'Budaya',
    'deskripsi' => 'Kampung Adat Dukuh adalah sebuah desa adat yang unik dan terpencil, terletak di Desa Cijambe, Kecamatan Cikelet, Garut. Kampung ini dikenal karena kehidupannya yang sangat sederhana dan memegang teguh tradisi leluhur, menjadikannya salah satu warisan budaya Sunda yang masih lestari.',
    'alamat' => 'Pananjung, Kec. Tarogong Kaler, Kabupaten Garut, Jawa Barat',
    'latitude' => '-7.1742987',
    'longitude' => '107.8840598',
    'foto' => 'lokasi/skCpApP1CaBqaTPYImX5IzMoZsQRXItEgz0lEsjQ.png',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T15:00:42.000000Z',
    'updated_at' => '2025-09-03T15:00:42.000000Z',
  ),
  53 => 
  array (
    'nama_lokasi' => 'Makam Godog - Prabu Kian Santang',
    'kategori' => 'Budaya',
    'deskripsi' => 'Makam Sunan Rohmat Suci adalah sebuah situs ziarah yang sangat penting dan sakral di Kabupaten Garut. Makam ini lebih dikenal dengan sebutan Makam Godog, yang berlokasi di Desa Lebak Agung, Kecamatan Karangpawitan. Situs ini dipercaya sebagai tempat pemakaman Prabu Kian Santang, putra dari Prabu Siliwangi dari Kerajaan Pajajaran, yang setelah masuk Islam kemudian berganti nama menjadi Sunan Rohmat Suci.',
    'alamat' => 'Lebakagung, Kec. Karangpawitan, Kabupaten Garut, Jawa Barat',
    'latitude' => '-7.2471917',
    'longitude' => '107.9531304',
    'foto' => 'lokasi/sPXuCRb4U4FChn6gkHd7wZXKf8jYdmDmY5OW1GKU.png',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T15:05:54.000000Z',
    'updated_at' => '2025-09-03T15:05:54.000000Z',
  ),
  54 => 
  array (
    'nama_lokasi' => 'Makam Godog Sunan Rahmat Suci',
    'kategori' => 'Budaya',
    'deskripsi' => 'Makam Godog adalah sebuah situs ziarah yang sangat penting dan sakral di Kabupaten Garut. Secara resmi dikenal sebagai Makam Sunan Rohmat Suci, situs ini berlokasi di Desa Lebak Agung, Kecamatan Karangpawitan. Tempat ini diyakini sebagai tempat pemakaman Prabu Kian Santang, putra dari Prabu Siliwangi dari Kerajaan Pajajaran, yang setelah masuk Islam kemudian bergelar Sunan Rohmat Suci.',
    'alamat' => 'Godog, Kec. Karangpawitan, Kabupaten Garut, Jawa Barat 44182',
    'latitude' => '-7.2512361',
    'longitude' => '107.9552976',
    'foto' => 'lokasi/uqtFAXl4Sd21Hqoq1YbgFbDuhDIfA5AD2bVGEZoZ.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T15:07:12.000000Z',
    'updated_at' => '2025-09-03T15:07:12.000000Z',
  ),
  55 => 
  array (
    'nama_lokasi' => 'Situs Ciburuy',
    'kategori' => 'Budaya',
    'deskripsi' => 'Situs Ciburuy adalah sebuah situs bersejarah dan cagar budaya yang sangat penting di Garut. Berlokasi di Desa Pamalayan, Kecamatan Bayongbong, situs ini dikenal sebagai pusat penyimpanan dan pelestarian manuskrip kuno peninggalan Kerajaan Pajajaran yang ditulis dalam aksara dan bahasa Sunda kuno. Situs ini sering dikaitkan dengan tokoh legendaris Prabu Kian Santang dan Prabu Siliwangi.',
    'alamat' => 'Pamalayan Kulon, Bayongbong, Pamalayan, Garut, Kabupaten Garut, Jawa Barat 44162',
    'latitude' => '-7.2945838',
    'longitude' => '107.8236712',
    'foto' => 'lokasi/uRxTI4RRWPz3r0QIMcehtZEu87vbSUlNYyJnZcCR.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T15:08:53.000000Z',
    'updated_at' => '2025-09-03T15:08:53.000000Z',
  ),
  56 => 
  array (
    'nama_lokasi' => 'Makam Keramat Cinunuk',
    'kategori' => 'Budaya',
    'deskripsi' => 'Makam Keramat Cinunuk adalah sebuah situs ziarah yang sangat penting di Kabupaten Garut, yang berlokasi di Desa Cinunuk, Kecamatan Wanaraja. Situs ini merupakan tempat pemakaman Raden Wangsa Muhammad, seorang tokoh penyebar agama Islam yang dikenal dengan julukan Pangeran Papak. Nama "Papak" sendiri memiliki arti "rata" atau "seimbang", yang dipercaya merujuk pada sikap beliau yang adil dan sama rata terhadap semua orang. Makam ini menjadi destinasi wisata religi yang ramai dikunjungi oleh para peziarah dari berbagai daerah, terutama pada waktu-waktu tertentu.',
    'alamat' => 'Cinunuk, Kec. Wanaraja, Kabupaten Garut, Jawa Barat 44183',
    'latitude' => '-7.1726323',
    'longitude' => '107.9663480',
    'foto' => 'lokasi/bNvQFypQYJ3YMT3WbZjideX9Qp9RfXuNR5RIcQOz.png',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T15:11:13.000000Z',
    'updated_at' => '2025-09-03T15:11:13.000000Z',
  ),
  57 => 
  array (
    'nama_lokasi' => 'Situs Pasir Lulumpang',
    'kategori' => 'Budaya',
    'deskripsi' => 'Situs Pasir Lulumpang adalah sebuah situs arkeologi dan geologi yang menarik di Garut, berlokasi di daerah Rancabango, Kecamatan Tarogong Kaler. Situs ini terkenal karena keberadaan "batu lulumpang," yaitu formasi batuan alami yang unik dan menyerupai alat tumbuk atau lumpang kuno.',
    'alamat' => 'Cimareme, Kec. Banyuresmi, Kabupaten Garut, Jawa Barat 44191',
    'latitude' => '-7.1211813',
    'longitude' => '107.9494015',
    'foto' => 'lokasi/RbI4sRc1rOR8SPRhcl2CoXpQ4xW4btZL2KFdgC1d.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T15:12:44.000000Z',
    'updated_at' => '2025-09-03T15:12:44.000000Z',
  ),
  58 => 
  array (
    'nama_lokasi' => 'Babancong Garut',
    'kategori' => 'Budaya',
    'deskripsi' => 'Babancong adalah salah satu ikon bersejarah dan cagar budaya yang sangat penting di Garut. Berlokasi di kompleks Pendopo Kabupaten Garut, di Jalan Dewi Sartika, Kecamatan Garut Kota, bangunan ini berdiri megah di antara Lapangan Otto Iskandardinata dan rumah dinas Bupati Garut. Secara harfiah, "babancong" dalam bahasa Sunda berarti panggung kecil. Bangunan ini memiliki arsitektur unik, berbentuk panggung segi delapan dengan delapan pilar yang menyangga atapnya.',
    'alamat' => 'Jl. Kabupaten Garut No.15, Paminggir, Kec. Garut Kota, Kabupaten Garut, Jawa Barat 44118',
    'latitude' => '-7.2166552',
    'longitude' => '107.9014107',
    'foto' => 'lokasi/Wg6RCmmoAyhHhpz17JJJsbSonyz8KNixCtDRbL3j.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T15:16:00.000000Z',
    'updated_at' => '2025-09-03T15:16:00.000000Z',
  ),
  59 => 
  array (
    'nama_lokasi' => 'Gedung Pendopo Kabupaten Garut',
    'kategori' => 'Budaya',
    'deskripsi' => 'Gedung Pendopo Garut adalah kompleks kantor dan rumah dinas resmi Bupati Garut. Bangunan ini tidak hanya berfungsi sebagai pusat pemerintahan daerah, tetapi juga merupakan salah satu ikon sejarah dan arsitektur yang paling penting di Kabupaten Garut. Gedung ini terletak di pusat kota, berhadapan langsung dengan Alun-alun Garut dan Babancong yang ikonik.',
    'alamat' => 'Jl. Kiansantang No.2, Paminggir, Kec. Garut Kota, Kabupaten Garut, Jawa Barat 44118',
    'latitude' => '-7.2172226',
    'longitude' => '107.9012115',
    'foto' => 'lokasi/yaEGr7Kr9s5IJtZyyUHpqgLqkgSmNJL4VpXsaJXp.jpg',
    'ticket_url' => NULL,
    'created_at' => '2025-09-03T15:17:13.000000Z',
    'updated_at' => '2025-09-03T15:17:13.000000Z',
  ),
));
    }
}